Feat/click listeners
nattsnb/vite-calcualtor pull request #1
Opened 2024-06-20 12:31 UTC by nattsnb

2024-07-03 11:40 UTC, Solnick commented on Calculator.js
> +        row.append(buttonContainer);
```suggestion
    for (let i = 0; i < buttonsArray.length; i++) {
      const buttonContainer = document.createElement("div");
      row.append(buttonContainer);
      if (Number(buttonsArray[i])) {
        new DigitButton(
            buttonsArray[i],
            this,
            buttonContainer,
        );
      }
      else {
```

2024-07-03 11:40 UTC, Solnick commented on Calculator.js
> +        row.append(buttonContainer);
duplicate code which can be elevated outside of the if statement

2024-07-03 11:40 UTC, Solnick commented on Input.js
> +    this.num2 = null;
`num1` and `num2` are poor names for object properties. I have no idea what it represents.

2024-07-03 11:40 UTC, Solnick commented on Input.js
> +    if (eq === "=") {
This function is hard to follow. Can you describe why we need all of this if statements? Then, from this point we can think of improving the readability.

Also get rid of the console.logs

2024-07-03 19:27 UTC, Solnick requested changes
What about rest of the comments?

2024-07-03 19:27 UTC, Solnick commented on Calculator.js
> +      const buttonContainer = document.createElement("div");
The code djplicate is still there, but now it is executed twice

2024-07-04 11:23 UTC, nattsnb commented on Input.js
> +    if (eq === "=") {
yes, I think the statements are needed to fool prove the application. they prevent the app from bugging. deleted 2 of them from first statement, and added one more later, as I've found another bug trying to check if all are needed

2024-07-05 09:07 UTC, Solnick requested changes
please change code according to comments

2024-07-29 07:40 UTC, merged